_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test",("inversetext_test",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 1e-5
  LR_BACKBONE: 1e-6
  WARMUP_ITERS: 0
  STEPS: (8000,)  # no step
  MAX_ITER: 6000
  CHECKPOINT_PERIOD: 1000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/finetune/totaltext"