_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/pretrain/model_final.pth"
  ViTAEv2:
    DROP_PATH_RATE: 0.2

DATASETS:
  TRAIN: ("totaltext_train",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 1e-5
  LR_BACKBONE: 5e-6
  WARMUP_ITERS: 0
  STEPS: (100000,)
  MAX_ITER: 5000
  CHECKPOINT_PERIOD: 2000

TEST:
  EVAL_PERIOD: 1000

OUTPUT_DIR: "output/vitaev2_s/150k_tt_mlt_13_15_textocr/finetune/totaltext"