_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "pretrained_backbone/swin_tiny_patch4_window7_224_convert.pth"

DATASETS:
  TRAIN: ("syntext1","syntext2","totaltext_train","mlt","ic13_train","ic15_train",,"textocr1","textocr2",)
  TEST: ("totaltext_test",)

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 1e-4
  LR_BACKBONE: 5e-5
  WARMUP_ITERS: 0
  STEPS: (320000,)
  MAX_ITER: 375000
  CHECKPOINT_PERIOD: 100000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "output/SwinT/150k_tt_mlt_13_15/3090_pretrain"