_BASE_: "../Base_det.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/torchvision/R-50.pkl"

DATASETS:
  TRAIN: ("syntext1","syntext2","totaltext_train","mlt","ic13_train","ic15_train","textocr1","textocr2",) 
  # TEST: ("totaltext_test",) 
  TEST: ("totaltext_test","inversetext_test",) 

SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 2e-4
  LR_BACKBONE: 2e-5
  WARMUP_ITERS: 0
  STEPS: (375000,)
  MAX_ITER: 435000
  CHECKPOINT_PERIOD: 100000

TEST:
  EVAL_PERIOD: 10000

OUTPUT_DIR: "output/R50/150k_tt_mlt_13_15_textocr/pretrain"
